# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate:     1

# About/contact
author:
  name:       Author name
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown

# Page generator plugin
page_gen:
  - data: 'drugs'
    template: 'medicament'
    name: 'cis_code'
    dir: 'medicament'